#ifndef COMMON_H
#define COMMON_H

// define colors

#define WHITE 0
#define YELLOW 1 
#define GREEN 2
#define BLUE 3
#define RED 4
#define ORANGE 5

// define positions (within face)

#define TOP_LEFT 0
#define TOP_MIDDLE 3
#define TOP_RIGHT 6
#define MIDDLE_LEFT 9
#define CENTER 12
#define MIDDLE_RIGHT 15
#define BOTTOM_LEFT 18
#define BOTTOM_MIDDLE 21
#define BOTTOM_RIGHT 24

// clears, equivalent to 32 - position - 3
#define CLEAR_TOP_LEFT 29
#define CLEAR_TOP_MIDDLE 26
#define CLEAR_TOP_RIGHT 23
#define CLEAR_MIDDLE_LEFT 20
#define CLEAR_CENTER 17
#define CLEAR_MIDDLE_RIGHT 14
#define CLEAR_BOTTOM_LEFT 11
#define CLEAR_BOTTOM_MIDDLE 8
#define CLEAR_BOTTOM_RIGHT 5

#define CLEAR 29

// define faces
#define WHITE_FACE (WHITE << TOP_LEFT) + (WHITE << TOP_MIDDLE) + (WHITE << TOP_RIGHT) + (WHITE << MIDDLE_LEFT) + (WHITE << CENTER) + (WHITE << MIDDLE_RIGHT) + (WHITE << BOTTOM_LEFT) + (WHITE << BOTTOM_MIDDLE) + (WHITE << BOTTOM_RIGHT)
#define YELLOW_FACE (YELLOW << TOP_LEFT) + (YELLOW << TOP_MIDDLE) + (YELLOW << TOP_RIGHT) + (YELLOW << MIDDLE_LEFT) + (YELLOW << CENTER) + (YELLOW << MIDDLE_RIGHT) + (YELLOW << BOTTOM_LEFT) + (YELLOW << BOTTOM_MIDDLE) + (YELLOW << BOTTOM_RIGHT)
#define GREEN_FACE (GREEN << TOP_LEFT) + (GREEN << TOP_MIDDLE) + (GREEN << TOP_RIGHT) + (GREEN << MIDDLE_LEFT) + (GREEN << CENTER) + (GREEN << MIDDLE_RIGHT) + (GREEN << BOTTOM_LEFT) + (GREEN << BOTTOM_MIDDLE) + (GREEN << BOTTOM_RIGHT)
#define BLUE_FACE (BLUE << TOP_LEFT) + (BLUE << TOP_MIDDLE) + (BLUE << TOP_RIGHT) + (BLUE << MIDDLE_LEFT) + (BLUE << CENTER) + (BLUE << MIDDLE_RIGHT) + (BLUE << BOTTOM_LEFT) + (BLUE << BOTTOM_MIDDLE) + (BLUE << BOTTOM_RIGHT)
#define RED_FACE (RED << TOP_LEFT) + (RED << TOP_MIDDLE) + (RED << TOP_RIGHT) + (RED << MIDDLE_LEFT) + (RED << CENTER) + (RED << MIDDLE_RIGHT) + (RED << BOTTOM_LEFT) + (RED << BOTTOM_MIDDLE) + (RED << BOTTOM_RIGHT)
#define ORANGE_FACE (ORANGE << TOP_LEFT) + (ORANGE << TOP_MIDDLE) + (ORANGE << TOP_RIGHT) + (ORANGE << MIDDLE_LEFT) + (ORANGE << CENTER) + (ORANGE << MIDDLE_RIGHT) + (ORANGE << BOTTOM_LEFT) + (ORANGE << BOTTOM_MIDDLE) + (ORANGE << BOTTOM_RIGHT)

#endif